services:
  db:
    image: postgres:16-alpine
    container_name: autoflex-db
    ports:
      - "5434:5432"
    environment:
      - POSTGRES_DB=autoflexdb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - autoflex-network

  pgadmin:
    image: dpage/pgadmin4
    container_name: autoflex-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - db
    networks:
      - autoflex-network

volumes:
  postgres_data:


networks:
  autoflex-network:
    driver: bridge
